name: main

on:
  push:

jobs:
  lint:
    name: Check - Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v2.1.5
      - name: Install packages
        run: npm ci --no-fund
      - name: Run ESLint
        run: npx eslint --ext .js,.ts .
  build:
    name: Transpile TypeScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v2.1.5
      - name: Install packages
        run: npm ci --no-fund
      - name: transpile TypeScript
        run: npx tsc
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: lib
          path: |
            dist
            !dist/test
  test:
    name: Coverage with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node: ["14", "16"]
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}
      - name: Install packages
        run: npm ci --no-fund
      - name: Collect coverage
        run: npm run coverage
  release:
    name: Semantic Release
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - lint
      - build
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2.1.5
      - name: Install packages
        run: npm ci --no-fund
      - name: Download lib from build job
        uses: actions/download-artifact@v2.0.10
        with:
          name: lib
          path: dist/
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
